version: '3.8'
services:
  php:
    build: ./docker/php
    ports:
      - '80:80'
    volumes:
      - '.:/var/www'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached'
      - './docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:cached'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  mysql:
    image: 'registry.hub.docker.com/library/mysql:8.0.33'
    volumes:
      - './docker-data/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      -  MYSQL_DATABASE=demo
      -  MYSQL_DATABASE=root
      -  MYSQL_ROOT_PASSWORD=root
